### ISSUE TITLE
Reference to home directory

### ISSUE THREAD

**Issue by Arelav** [nassendelft/alfred-android-emulator#2]
I'm using Alfred on two separate computers however the settings are synced.
How can I specify a reference to the $HOME without providing an exact path?
For example, my Android emulator located in `/Users/[MY_USERNAME]/Library/Android/sdk/emulator/emulator`
and I need something like
`~/Library/Android/sdk/emulator/emulator`
or
`${HOME}/Library/Android/sdk/emulator/emulator`
both options is not picked up only full path works but it's different on two machines.

**Comment by Arelav** [comment]
I'm not familiar with Python and can't suggest a good PR with optional reference relative to the HOME.
I made a small change locally to be always relative to the home directory. I'll be appreciate if this option will supported somehow with workflow settings.

This is my change always pointing to the home

```
from os.path import expanduser

home = expanduser("~")

path = getenv('emu_path')

emulators = check_output([home + path, "-list-avds"]).decode("utf-8").rstrip().split('\n')
```

**Comment by Arelav** [comment]
Also it finds the list of emulator however don't launch without change in bash script to 
`$HOME$emu_path @{query}`

**Comment by nassendelft** [comment]
I've just fixed this for you. Should be online shortly
